name: Flutter Windows Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Windows application
        run: flutter build windows

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build/windows/runner/Release/
